# command line: main.py --config /datadrive3/DeGCN_pytorch/work_dir/ntu120/csub/degcn/config.yaml --work-dir work_dir/ntu120/csub/degcn --phase test --save-score True --weights work_dir/ntu120/csub/degcn/20250217_233519/epoch_80_78720.pt --device 0

base_lr: 0.1
batch_size: 64
config: /datadrive3/DeGCN_pytorch/work_dir/ntu120/csub/degcn/config.yaml
cosine_epoch: 60
device:
- 0
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
half: true
ignore_weights: []
log_interval: 100
model: model.degcn.Model
model_args:
  eta: 4
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  k: 8
  num_class: 120
  num_person: 2
  num_point: 25
  num_stream: 2
model_saved_name: ''
nesterov: true
num_epoch: 80
num_worker: 0
optimizer: SGD
phase: test
print_log: true
save_epoch: 0
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 60
- 75
test_batch_size: 64
test_feeder_args:
  FPS: 3
  bone: false
  chunks: 1
  data_path: data/ntu120/NTU120_CSub.npz
  debug: false
  decimation_frequency: 10
  mitigation: true
  p_interval:
  - 0.95
  random_degradation_type: interpolate
  random_miss: true
  random_miss_amount: 0.9
  spatial_deg: False
  split: test
  structured_degradation: false
  structured_degradation_type: frame_rate
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/ntu120/NTU120_CSub.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: true
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: work_dir/ntu120/csub/degcn/20250217_233519/epoch_80_78720.pt
work_dir: work_dir/ntu120/csub/degcn
